# Generated by Django 4.2.6 on 2023-10-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesection',
            name='title',
            field=models.CharField(default='', verbose_name=100),
        ),
    ]
